/**
 * MySQL **executable comment** version gates.
 *
 * `/*!NNNNN sql &#42;/` is not a comment: MySQL executes the enclosed SQL when
 * the running server's version is at least `NNNNN`
 * (`major*10000 + minor*100 + patch`), and skips it otherwise. Any other
 * SQL engine — and `mysql`'s own `--comments`-stripping paths — sees an
 * ordinary comment. That is what lets one dump file carry statements only
 * newer servers understand while still restoring on older ones.
 *
 * Every number below is the version that introduced the feature the guarded
 * statement needs, which is why they are named rather than inlined. They are
 * **not** the version of the server being dumped: a dump taken from MySQL
 * 8.4 still writes `/*!40101 SET @OLD_SQL_MODE=... &#42;/`, because the point of
 * the gate is "any server from 4.1.1 onwards can execute this", not "this
 * came from 4.1.1". Substituting the source server's version would make the
 * dump silently skip its own session guards on every older target — the
 * exact opposite of the intent.
 *
 * These match the gates `mysqldump` emits, verified against the reference
 * dumps in `test-output/reference/` generated by MySQL 8.0 and 8.4.
 */

/** MySQL 3.23.12 — `CREATE DATABASE ... IF NOT EXISTS`. */
export const GATE_CREATE_DATABASE_IF_NOT_EXISTS = 32312;

/** MySQL 4.0.0 — `ALTER TABLE ... DISABLE KEYS` / `ENABLE KEYS`. */
export const GATE_ALTER_TABLE_KEYS = 40000;

/** MySQL 4.1.0 — `START TRANSACTION WITH CONSISTENT SNAPSHOT`. */
export const GATE_CONSISTENT_SNAPSHOT = 40100;

/** MySQL 4.1.1 — session character-set variables and `SQL_MODE`. */
export const GATE_CHARSET_AND_SQL_MODE = 40101;

/** MySQL 4.1.1 — `DEFAULT CHARACTER SET` on `CREATE DATABASE`. */
export const GATE_DATABASE_DEFAULT_CHARSET = 40100;

/** MySQL 4.1.3 — `TIME_ZONE`. */
export const GATE_TIME_ZONE = 40103;

/** MySQL 4.1.4 — `UNIQUE_CHECKS` and `FOREIGN_KEY_CHECKS`. */
export const GATE_CHECKS = 40014;

/** MySQL 4.1.11 — `SQL_NOTES`. */
export const GATE_SQL_NOTES = 40111;

/** MySQL 5.0.1 — views (`CREATE VIEW`, `DROP VIEW`). */
export const GATE_VIEWS = 50001;

/** MySQL 5.0.3 — stored routines and triggers, and their session context. */
export const GATE_STORED_PROGRAMS = 50003;

/** MySQL 5.0.13 — the `DEFINER` clause on a view. */
export const GATE_VIEW_DEFINER = 50013;

/** MySQL 5.0.17 — the `DEFINER` clause on a trigger. */
export const GATE_TRIGGER_DEFINER = 50017;

/** MySQL 5.1.6 — events (`CREATE EVENT`). */
export const GATE_EVENTS = 50106;

/** MySQL 5.1.17 — the `DEFINER` clause on an event. */
export const GATE_EVENT_DEFINER = 50117;

/** MySQL 5.5.3 — `utf8mb4`, and therefore `SET NAMES utf8mb4`. */
export const GATE_UTF8MB4 = 50503;

/** MySQL 8.0.16 — `DEFAULT ENCRYPTION` on `CREATE DATABASE`. */
export const GATE_DATABASE_ENCRYPTION = 80016;

/**
 * Wraps `sql` in an executable comment gated at `version`.
 *
 * The rendering is `/*!NNNNN <sql> &#42;/` with exactly one space on each side,
 * matching `mysqldump`. The version is zero-padded to five digits because
 * MySQL's parser reads exactly five digits after `!`; a four-digit number
 * would be interpreted as the start of the SQL.
 */
export function executableComment(version: number, sql: string): string {
  return `/*!${String(version).padStart(5, '0')} ${sql} */`;
}

/**
 * Like {@link executableComment} but with no space before the closing
 * delimiter. `mysqldump` writes its view `DROP`/`CREATE` statements this way
 * (`/*!50001 DROP VIEW IF EXISTS \`v\`&#42;/;`), and the difference is preserved
 * so structural comparisons against native output do not report noise.
 */
export function executableCommentTight(version: number, sql: string): string {
  return `/*!${String(version).padStart(5, '0')} ${sql}*/`;
}
